version: 0.2

env:
  variables:
    bucket: "s3://ampatchlab/CodeBuild/nf-rnaseq"
  parameter-store:
    AWS_ACCESS_KEY_ID: "/CodeBuild/AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "/CodeBuild/AWS_SECRET_ACCESS_KEY"
    AWS_DEFAULT_REGION: "/CodeBuild/AWS_DEFAULT_REGION"

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - apt-get update -y
      - apt-get install -y graphviz
  pre_build:
    commands:
      - aws s3 rm --quiet --recursive "$bucket"
  build:
    commands:
      - curl -fsSL get.nextflow.io | bash
      - |
        ./nextflow run . \
          -ansi-log false \
          -profile awsbatch,HBR_UHR_ERCC-SE \
          -work-dir "$bucket/work" \
          --refdir "$bucket/reference" \
          --outdir "$bucket/results" \
          --aws_region "$AWS_DEFAULT_REGION" \
          --aws_queue "nf-rnaseq"
  post_build:
    commands:
      - aws s3 sync --quiet ./reports "$bucket/reports"
